### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by shirodreaming** [elvis972602/Kemono-scraper#17]
My sincerest apologies for asking this under "Issues" but I would love to use this tool, but I have no idea how to install/use it. Would it be possible to create a tutorial? All I really need guidance on is how to set it up. Sorry again!

**Comment by elvis972602** [comment]
Download it in [Release](https://github.com/elvis972602/Kemono-scraper/releases) , you can use the flags or the config file to set it
# Flag
Start with a terminal, for example  
```
kemono-scraper.exe -link <url> -async -max-download-parallel 5
```
# Config file
Create a file called config.yaml, and then you can copy the following example. 
```yaml
link: <url>
banner: true
async: true
max-download-parallel: 5
output: ./downloads
template: "[<ks:service>] <ks:creator>/<ks:post>/<ks:filename><ks:extension>"
image-template: "[<ks:service>] <ks:creator>/<ks:post>/<ks:index><ks:extension>"
video-template: "[<ks:service>] <ks:creator>/<ks:post>/video/<ks:filename><ks:extension>"
retry: 10
retry-interval: 15
# proxy: socks5://proxy:1080
```
then doubleclick kemono-scraper.exe to start it

You can also find more options in the [Readme](https://github.com/elvis972602/Kemono-scraper/blob/master/README.md)
